### ISSUE TITLE
Error:(20, 9) value of type 'CCNPreferencesWindowController' has no member 'viewControllers'

### ISSUE THREAD

**Issue by SantoDE** [phranck/CCNPreferencesWindowController#15]
Hey there,

I'm currently trying to get this implemented properly. However, I'm struggling. Here's my code example:

```
import Cocoa
import CCNPreferencesWindowController

@NSApplicationMain
class AppDelegate: NSObject, NSApplicationDelegate {

    private let settingsController = SettingsPreferencesController()

    private var preferencesController = CCNPreferencesWindowController()

    func applicationDidFinishLaunching(aNotification: NSNotification) {
        preferencesController.viewControllers = [settingsController]
        preferencesController.centerToolbarItems  = true
    }
}
```

What am I doing wrong?

Thanks a lot!

**Comment by iamDecode** [comment]
I experienced the same issue when using the library with cocoapods. The obj-c and Swift api's clash and are not consistent (view controllers (Swift) vs. setPreferencesViewControllers() (obj-c)). I temporarily solved this by copying the files into my project like the example did, that might work for ya.

**Comment by SantoDE** [comment]
@iamDecode THANKS A LOT MAN! I can now compile it. You probably saved my day 👍

**Comment by phranck** [comment]
Hey Guys!

First: thanks for using this control, I appreciate it a lot. So, currently I'm not familar with Swift since I'm a fulltime ObjC guy 😉. The Swift implementation isn't originated by myself and honestly I lost it through sheer negligence to review and proof it in detail. Sorry for the trouble!

If you are willing and can spent a bit of time please feel free to fix it and make it consistent to the objc version. This would really help me (and a lot of other developers, too). Thanks again!
